# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Icarus\learning\VS-codes\Jupyter\明日方舟抽卡分析\断点更新\抽卡分析.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWebEngineWidgets import QWebEngineView
from PyQt5.QtCore import QUrl

class Ui_Arknights(object):
    def setupUi(self, Arknights):
        Arknights.setObjectName("Arknights")
        Arknights.resize(1341, 711)
        self.gridLayout_2 = QtWidgets.QGridLayout(Arknights)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.webBrowser = QWebEngineView(Arknights)
        self.webBrowser.setEnabled(True)
        self.webBrowser.setObjectName("webBrowser")
        self.gridLayout_2.addWidget(self.webBrowser, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.url_lineEdit = QtWidgets.QLineEdit(Arknights)
        self.url_lineEdit.setText("")
        self.url_lineEdit.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.url_lineEdit.setObjectName("url_lineEdit")
        self.gridLayout.addWidget(self.url_lineEdit, 1, 3, 1, 2)
        self.username_label = QtWidgets.QLabel(Arknights)
        self.username_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.username_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.username_label.setObjectName("username_label")
        self.gridLayout.addWidget(self.username_label, 0, 2, 1, 1)
        self.PromptBox = QtWidgets.QLineEdit(Arknights)
        self.PromptBox.setMouseTracking(True)
        self.PromptBox.setFrame(False)
        self.PromptBox.setAlignment(QtCore.Qt.AlignCenter)
        self.PromptBox.setReadOnly(True)
        self.PromptBox.setObjectName("PromptBox")
        self.gridLayout.addWidget(self.PromptBox, 2, 0, 1, 1)
        self.username_lineEdit = QtWidgets.QLineEdit(Arknights)
        self.username_lineEdit.setObjectName("username_lineEdit")
        self.gridLayout.addWidget(self.username_lineEdit, 0, 3, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(613, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.ExtractExcelBTN = QtWidgets.QPushButton(Arknights)
        self.ExtractExcelBTN.setObjectName("ExtractExcelBTN")
        self.gridLayout.addWidget(self.ExtractExcelBTN, 2, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(613, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        self.url_label = QtWidgets.QLabel(Arknights)
        self.url_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.url_label.setObjectName("url_label")
        self.gridLayout.addWidget(self.url_label, 1, 2, 1, 1)
        self.ClassifyBTN = QtWidgets.QPushButton(Arknights)
        self.ClassifyBTN.setObjectName("ClassifyBTN")
        self.gridLayout.addWidget(self.ClassifyBTN, 2, 3, 1, 1)
        self.RenewDataBTN = QtWidgets.QPushButton(Arknights)
        self.RenewDataBTN.setObjectName("RenewDataBTN")
        self.gridLayout.addWidget(self.RenewDataBTN, 2, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.username_label.setBuddy(self.username_lineEdit)
        self.url_label.setBuddy(self.url_lineEdit)

        self.retranslateUi(Arknights)
        self.ClassifyBTN.clicked.connect(Arknights.ViewData)
        self.ExtractExcelBTN.clicked.connect(Arknights.ExtractExcel)
        self.RenewDataBTN.clicked.connect(Arknights.RenewData)
        QtCore.QMetaObject.connectSlotsByName(Arknights)

    def retranslateUi(self, Arknights):
        _translate = QtCore.QCoreApplication.translate
        Arknights.setWindowTitle(_translate("Arknights", "Form"))
        self.url_lineEdit.setPlaceholderText(_translate("Arknights", "请输入数据链接"))
        self.username_label.setText(_translate("Arknights", "用户名"))
        self.PromptBox.setText(_translate("Arknights", "[提示框]用户名仅用于区分不同账号，无需与游戏内用户名一致"))
        self.username_lineEdit.setPlaceholderText(_translate("Arknights", "请输入用户名"))
        self.ExtractExcelBTN.setText(_translate("Arknights", "导出excel"))
        self.url_label.setText(_translate("Arknights", "数据链接"))
        self.ClassifyBTN.setText(_translate("Arknights", "寻访分类"))
        self.RenewDataBTN.setText(_translate("Arknights", "获取数据"))
