# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Icarus\learning\VS-codes\Jupyter\明日方舟抽卡分析\断点更新\寻访标注.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NoteSearchWindow(object):
    def setupUi(self, NoteSearchWindow):
        NoteSearchWindow.setObjectName("NoteSearchWindow")
        NoteSearchWindow.resize(627, 200)
        self.gridLayout_2 = QtWidgets.QGridLayout(NoteSearchWindow)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(NoteSearchWindow)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.NameEdit = QtWidgets.QLineEdit(NoteSearchWindow)
        self.NameEdit.setObjectName("NameEdit")
        self.gridLayout.addWidget(self.NameEdit, 0, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(NoteSearchWindow)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.BeginEdit = QtWidgets.QLineEdit(NoteSearchWindow)
        self.BeginEdit.setObjectName("BeginEdit")
        self.gridLayout.addWidget(self.BeginEdit, 1, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(NoteSearchWindow)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.EndEdit = QtWidgets.QLineEdit(NoteSearchWindow)
        self.EndEdit.setObjectName("EndEdit")
        self.gridLayout.addWidget(self.EndEdit, 2, 1, 1, 2)
        self.OkBTN = QtWidgets.QPushButton(NoteSearchWindow)
        self.OkBTN.setObjectName("OkBTN")
        self.gridLayout.addWidget(self.OkBTN, 3, 1, 1, 1)
        self.CloseBTN = QtWidgets.QPushButton(NoteSearchWindow)
        self.CloseBTN.setObjectName("CloseBTN")
        self.gridLayout.addWidget(self.CloseBTN, 3, 2, 1, 1)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setColumnStretch(1, 5)
        self.gridLayout.setColumnStretch(2, 5)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(NoteSearchWindow)
        self.OkBTN.clicked.connect(NoteSearchWindow.SendNote)
        self.CloseBTN.clicked.connect(NoteSearchWindow.close)
        QtCore.QMetaObject.connectSlotsByName(NoteSearchWindow)

    def retranslateUi(self, NoteSearchWindow):
        _translate = QtCore.QCoreApplication.translate
        NoteSearchWindow.setWindowTitle(_translate("NoteSearchWindow", "Form"))
        self.label.setText(_translate("NoteSearchWindow", "寻访名称"))
        self.NameEdit.setPlaceholderText(_translate("NoteSearchWindow", "请输入本次标注的寻访类别名称，例如“盛夏新星”“遗愿焰火”"))
        self.label_2.setText(_translate("NoteSearchWindow", "起始编号"))
        self.BeginEdit.setPlaceholderText(_translate("NoteSearchWindow", "请输入想要标注的数据起始编号"))
        self.label_3.setText(_translate("NoteSearchWindow", "结束编号"))
        self.EndEdit.setPlaceholderText(_translate("NoteSearchWindow", "请输入想要标注的数据结束编号"))
        self.OkBTN.setText(_translate("NoteSearchWindow", "确定"))
        self.CloseBTN.setText(_translate("NoteSearchWindow", "取消"))
