# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Icarus\learning\VS-codes\Jupyter\明日方舟抽卡分析\断点更新\标注移除.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RemoveNote(object):
    def setupUi(self, RemoveNote):
        RemoveNote.setObjectName("RemoveNote")
        RemoveNote.resize(627, 200)
        self.gridLayout_2 = QtWidgets.QGridLayout(RemoveNote)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(RemoveNote)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(RemoveNote)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 0, 1, 1, 1)
        self.OkBTN = QtWidgets.QPushButton(RemoveNote)
        self.OkBTN.setObjectName("OkBTN")
        self.gridLayout.addWidget(self.OkBTN, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(RemoveNote)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(RemoveNote)
        self.OkBTN.clicked.connect(RemoveNote.SendRemove)
        self.pushButton_2.clicked.connect(RemoveNote.close)
        QtCore.QMetaObject.connectSlotsByName(RemoveNote)

    def retranslateUi(self, RemoveNote):
        _translate = QtCore.QCoreApplication.translate
        RemoveNote.setWindowTitle(_translate("RemoveNote", "Form"))
        self.label.setText(_translate("RemoveNote", "移除寻访类别"))
        self.OkBTN.setText(_translate("RemoveNote", "确定"))
        self.pushButton_2.setText(_translate("RemoveNote", "取消"))
